/**
 * Itqān (إتقان) - Madani Qa'idah Master Dataset & Makhaarij Engine
 * Derived from docs/qaida.md
 * Spans 17 Makhaarij articulation points and 22 comprehensive lessons.
 */

export interface MakhrajDefinition {
  id: string;
  nameArabic: string;
  nameEnglish: string;
  category: 'Halqee' | 'Lisaani' | 'Shafawi' | 'Jawfee' | 'Khaysoom';
  categoryTitle: string;
  subRegion: string;
  letters: string[];
  lettersArabicName?: string;
  description: string;
  discoveryExample: string;
  tips: string[];
  acousticTag?: string;
}

export interface QaidaTile {
  id: string;
  arabic: string;
  spelledArabic?: string; // Hijjay spelling breakdown (e.g. مِيْمٌ زَبَر مَ)
  transliteration?: string;
  englishMeaning?: string;
  ruleTag?: 'heavy' | 'echo' | 'whistle' | 'nasal' | 'madd' | 'leen' | 'shaddah' | 'tanween' | 'normal';
  ruleNote?: string;
  targetLetter?: string;
}

export interface QaidaLesson {
  id: number;
  slug: string;
  titleArabic: string;
  titleEnglish: string;
  stage: 1 | 2 | 3 | 4;
  stageTitle: string;
  estimatedMinutes: number;
  summary: string;
  keyRules: string[];
  pedagogicalTips: string[];
  tiles: QaidaTile[];
  quiz?: {
    question: string;
    options: { text: string; correct: boolean; explanation: string }[];
  }[];
}

export const MAKHAARIJ_DATA: MakhrajDefinition[] = [
  {
    id: 'm-halq-1',
    nameArabic: 'أَقْصَى الْحَلْقِ',
    nameEnglish: 'Aqsa al-Halq (Bottom of Throat)',
    category: 'Halqee',
    categoryTitle: 'Throat (Halq)',
    subRegion: 'Deepest part of throat near vocal cords',
    letters: ['ء', 'ه'],
    lettersArabicName: 'حروف حلقية (Halqiyyah)',
    description: 'Pronounced from the bottom-most part of the throat near the chest / larynx.',
    discoveryExample: 'أَءْ / أَهْ',
    tips: [
      'For Hamzah (ء), produce a firm vocal stop without choking.',
      'For Haa (هـ), let natural airflow pass freely through relaxed vocal cords.',
    ],
    acousticTag: 'Laryngeal / Glottal',
  },
  {
    id: 'm-halq-2',
    nameArabic: 'وَسَطُ الْحَلْقِ',
    nameEnglish: 'Wasat al-Halq (Middle of Throat)',
    category: 'Halqee',
    categoryTitle: 'Throat (Halq)',
    subRegion: 'Middle throat / Pharyngeal constriction',
    letters: ['ع', 'ح'],
    lettersArabicName: 'حروف حلقية (Halqiyyah)',
    description: 'Pronounced from the middle of the throat by gently squeezing the pharyngeal muscles.',
    discoveryExample: 'أَعْ / أَحْ',
    tips: [
      'For Ayn (ع), constrict the epiglottis slightly toward the back wall of the throat.',
      'For Ha (ح), produce a crisp, dry breathy friction without vocal cord vibration.',
    ],
    acousticTag: 'Pharyngeal',
  },
  {
    id: 'm-halq-3',
    nameArabic: 'أَدْنَى الْحَلْقِ',
    nameEnglish: 'Adna al-Halq (Top of Throat)',
    category: 'Halqee',
    categoryTitle: 'Throat (Halq)',
    subRegion: 'Upper throat nearest to the oral cavity & uvula',
    letters: ['غ', 'خ'],
    lettersArabicName: 'حروف حلقية (Halqiyyah)',
    description: 'Pronounced from the top of the throat where it meets the back of the mouth/uvula.',
    discoveryExample: 'أَغْ / أَخْ',
    tips: [
      'Both Ghayn (غ) and Khaa (خ) are Mustaliyah (heavy) letters.',
      'Produce soft rasping friction at the root of the tongue meeting the soft palate.',
    ],
    acousticTag: 'Post-velar / Uvular',
  },
  {
    id: 'm-lisaan-1',
    nameArabic: 'أَقْصَى اللِّسَانِ - قَاف',
    nameEnglish: 'Deep Tongue Root (Qaaf)',
    category: 'Lisaani',
    categoryTitle: 'Tongue (Lisaan)',
    subRegion: 'Root of tongue & soft palate',
    letters: ['ق'],
    lettersArabicName: 'حروف لهوية (Lahawiyyah)',
    description: 'Pronounced from the extreme back/root of the tongue rising to touch the soft palate.',
    discoveryExample: 'أَقْ',
    tips: [
      'Qaaf is heavy (Musta’liyah) and exhibits Qalqala (echo) when Saakin.',
      'Do not confuse with Kaaf (ك); Qaaf touches the purely soft fleshy palate.',
    ],
    acousticTag: 'Uvular Plosive',
  },
  {
    id: 'm-lisaan-2',
    nameArabic: 'أَقْصَى اللِّسَانِ - كَاف',
    nameEnglish: 'Tongue Root Forward (Kaaf)',
    category: 'Lisaani',
    categoryTitle: 'Tongue (Lisaan)',
    subRegion: 'Root of tongue & hard/soft palate transition',
    letters: ['ك'],
    lettersArabicName: 'حروف لهوية (Lahawiyyah)',
    description: 'Pronounced from the back of the tongue touching the hard palate (slightly forward from Qaaf).',
    discoveryExample: 'أَكْ',
    tips: [
      'Kaaf is light (Muraqqaqah) with a gentle release of breath (Hams) upon release.',
    ],
    acousticTag: 'Velar Plosive',
  },
  {
    id: 'm-lisaan-3',
    nameArabic: 'وَسَطُ اللِّسَانِ',
    nameEnglish: 'Middle of Tongue (Jeem, Sheen, Yaa)',
    category: 'Lisaani',
    categoryTitle: 'Tongue (Lisaan)',
    subRegion: 'Center of tongue touching center of hard palate',
    letters: ['ج', 'ش', 'ي'],
    lettersArabicName: 'حروف شجرية (Shajariyyah)',
    description: 'Pronounced from the middle portion of the tongue raised against the hard roof of the mouth.',
    discoveryExample: 'أَجْ / أَشْ / أَيْ',
    tips: [
      'For Jeem (ج), close the passage completely with explosive release (Qalqala on Sukoon).',
      'For Sheen (ش), let air spread across the palate (Tafash-shi).',
      'For Yaa (ي), keep the air flowing smoothly without friction.',
    ],
    acousticTag: 'Palatal',
  },
  {
    id: 'm-lisaan-4',
    nameArabic: 'حَافَةُ اللِّسَانِ (ضَاد)',
    nameEnglish: 'Side / Edge of Tongue (Dhaad)',
    category: 'Lisaani',
    categoryTitle: 'Tongue (Lisaan)',
    subRegion: 'Lateral edges of tongue & upper molars',
    letters: ['ض'],
    lettersArabicName: 'حرف حافية (Haafiyyah)',
    description: 'Pronounced from one or both edges of the tongue pressed against the upper molar teeth.',
    discoveryExample: 'أَضْ',
    tips: [
      'Unique to the Arabic language (Lughat al-Dhad).',
      'Requires elongation of contact (Istitaalah) without turning into a standard Daal (د) or Dhaa (ظ).',
    ],
    acousticTag: 'Lateral-Alveolar',
  },
  {
    id: 'm-lisaan-5',
    nameArabic: 'طَرَفُ اللِّسَانِ - لَام',
    nameEnglish: 'Edge / Front Tip of Tongue (Laam)',
    category: 'Lisaani',
    categoryTitle: 'Tongue (Lisaan)',
    subRegion: 'Broad edge of tongue tip & upper gums',
    letters: ['ل'],
    lettersArabicName: 'حروف طرفية (Tarafiyyah)',
    description: 'Pronounced from the edge of the front tongue touching the gums of the top front teeth (premolar to premolar).',
    discoveryExample: 'أَلْ',
    tips: [
      'Light by default, except in the majestic Name of Allah (Ism-e-Jalalat) when preceded by Fathah/Dammah.',
    ],
    acousticTag: 'Alveolar Lateral',
  },
  {
    id: 'm-lisaan-6',
    nameArabic: 'طَرَفُ اللِّسَانِ - نُون',
    nameEnglish: 'Tongue Tip - Noon',
    category: 'Lisaani',
    categoryTitle: 'Tongue (Lisaan)',
    subRegion: 'Tip of tongue & gums of top 4 front teeth',
    letters: ['ن'],
    lettersArabicName: 'حروف طرفية (Tarafiyyah)',
    description: 'Pronounced from the tip of the tongue contacting the gums of the upper front teeth, accompanied by nasal resonance.',
    discoveryExample: 'أَنْ',
    tips: [
      'Noon has two components: oral occlusion at the gums and nasal Ghunnah from the Khaysoom.',
    ],
    acousticTag: 'Alveolar Nasal',
  },
  {
    id: 'm-lisaan-7',
    nameArabic: 'طَرَفُ اللِّسَانِ - رَاء',
    nameEnglish: 'Tongue Tip & Top Surface (Raa)',
    category: 'Lisaani',
    categoryTitle: 'Tongue (Lisaan)',
    subRegion: 'Tip and upper edge of tongue & upper gum ridge',
    letters: ['ر'],
    lettersArabicName: 'حروف طرفية (Tarafiyyah)',
    description: 'Pronounced from the tip and slight top surface of the tongue touching the upper gums with a single gentle tap.',
    discoveryExample: 'أَرْ',
    tips: [
      'Avoid excessive rolling/trilling (Takreer); limit to a clean single acoustic contact.',
    ],
    acousticTag: 'Alveolar Tap',
  },
  {
    id: 'm-lisaan-8',
    nameArabic: 'النِّطْعِيَّة (ط ، د ، ت)',
    nameEnglish: 'Nit\'iyyah (Twa, Daal, Taa)',
    category: 'Lisaani',
    categoryTitle: 'Tongue (Lisaan)',
    subRegion: 'Tip of tongue & roots of top 2 front incisors',
    letters: ['ط', 'د', 'ت'],
    lettersArabicName: 'حروف نطعية (Nit\'iyyah)',
    description: 'Pronounced from the tip of the tongue placed firmly against the gum line / root of the upper two front teeth.',
    discoveryExample: 'أَطْ / أَدْ / أَتْ',
    tips: [
      'Twa (ط) is heavy with back of tongue raised (Itbaaq & Isti’laa).',
      'Daal (د) and Taa (ت) are light (Tarqeeq).',
    ],
    acousticTag: 'Dento-Alveolar',
  },
  {
    id: 'm-lisaan-9',
    nameArabic: 'اللِّثَوِيَّة (ظ ، ذ ، ث)',
    nameEnglish: 'Lisawiyyah (Zhaa, Dhaal, Thaa)',
    category: 'Lisaani',
    categoryTitle: 'Tongue (Lisaan)',
    subRegion: 'Tip of tongue & edges of upper 2 front teeth',
    letters: ['ظ', 'ذ', 'ث'],
    lettersArabicName: 'حروف لثوية (Lisawiyyah)',
    description: 'Pronounced by slightly protruding the tip of the tongue to touch the edge/bottom of the upper front incisors.',
    discoveryExample: 'أَظْ / أَذْ / أَثْ',
    tips: [
      'Keep the tongue tip relaxed and softly contacting the teeth edges.',
      'Zhaa (ظ) is heavy; Dhaal (ذ) and Thaa (ث) are light.',
    ],
    acousticTag: 'Inter-Dental',
  },
  {
    id: 'm-lisaan-10',
    nameArabic: 'حُرُوفُ الصَّفِير (ص ، ز ، س)',
    nameEnglish: 'Safeeriyyah (Saad, Zay, Seen)',
    category: 'Lisaani',
    categoryTitle: 'Tongue (Lisaan)',
    subRegion: 'Tip of tongue behind lower & upper incisors',
    letters: ['ص', 'ز', 'س'],
    lettersArabicName: 'حروف أسلية / صفير (Safeeriyyah)',
    description: 'Pronounced from the tip of the tongue placed just behind the front lower teeth, producing a high-frequency whistle airflow.',
    discoveryExample: 'أَصْ / أَزْ / أَسْ',
    tips: [
      'Saad (ص) carries strong whistling + full mouth elevation (heavy).',
      'Seen (س) and Zay (ز) carry sharp, crisp light sibilance.',
    ],
    acousticTag: 'Sibilant Fricative',
  },
  {
    id: 'm-shafawi-1',
    nameArabic: 'بَاطِنُ الشَّفَةِ السُّفْلَى (فَاء)',
    nameEnglish: 'Lower Lip & Upper Teeth (Faa)',
    category: 'Shafawi',
    categoryTitle: 'Lips (Shafataan)',
    subRegion: 'Wet inner part of bottom lip & top 2 teeth',
    letters: ['ف'],
    lettersArabicName: 'حروف شفوية (Shafawiyyah)',
    description: 'Pronounced from the inside wet portion of the lower lip meeting the sharp edges of the top two front teeth.',
    discoveryExample: 'أَفْ',
    tips: [
      'Do not bite the dry outer lip; touch the inner moist portion gently with airflow.',
    ],
    acousticTag: 'Labio-Dental',
  },
  {
    id: 'm-shafawi-2',
    nameArabic: 'الشَّفَتَانِ (ب ، م ، و)',
    nameEnglish: 'Both Lips (Baa, Meem, Waw)',
    category: 'Shafawi',
    categoryTitle: 'Lips (Shafataan)',
    subRegion: 'Direct contact / rounding of both lips',
    letters: ['ب', 'م', 'و'],
    lettersArabicName: 'حروف شفوية (Shafawiyyah)',
    description: 'Baa (ب) from the wet inner lips closing firmly; Meem (م) from the dry outer lips closing gently; Waw (و) by complete rounding.',
    discoveryExample: 'أَبْ / أَمْ / أَوْ',
    tips: [
      'Baa: Firm closure with explosive Qalqala on Sukoon.',
      'Meem: Soft closure with nasal resonance (Ghunnah).',
      'Waw: Round lips into an "O" shape without touching the teeth.',
    ],
    acousticTag: 'Bilabial',
  },
  {
    id: 'm-jawfee',
    nameArabic: 'الْجَوْفُ (حُرُوفُ الْمَدّ)',
    nameEnglish: 'Al-Jawf (The Empty Oral Cavity)',
    category: 'Jawfee',
    categoryTitle: 'Oral Cavity (Jawf)',
    subRegion: 'Open unobstructed space of mouth and throat',
    letters: ['ا', 'و', 'ي'],
    lettersArabicName: 'حروف جوفية / مدية (Maddah)',
    description: 'Origin of prolonged vowels: Alif preceded by Fathah, Waw Saakin preceded by Dammah, Yaa Saakin preceded by Kasrah.',
    discoveryExample: 'نُوحِيهَا',
    tips: [
      'The sound resonates freely through the entire empty cavity for a duration of 2 Harakaat (1 Alif).',
    ],
    acousticTag: 'Vocalic Elongation',
  },
  {
    id: 'm-khaysoom',
    nameArabic: 'الْخَيْشُومُ (الْغُنَّة)',
    nameEnglish: 'Al-Khaysoom (The Nasal Cavity)',
    category: 'Khaysoom',
    categoryTitle: 'Nose (Khaysoom)',
    subRegion: 'Internal nasal passage connected to pharynx',
    letters: ['نّ', 'مّ', 'Ghunnah'],
    lettersArabicName: 'مخرج الغنة (Ghunnah)',
    description: 'The exclusive exit point for nasalization (Ghunnah), present in Noon & Meem Mushaddadah and Ikhfa/Idghaam.',
    discoveryExample: 'إِنَّ / ثُمَّ',
    tips: [
      'If you pinch your nose, the sound of Ghunnah will completely stop.',
    ],
    acousticTag: 'Nasal Resonance',
  },
];

export const QAIDA_LESSONS: QaidaLesson[] = [
  // ==========================================
  // STAGE 1: LETTERS, SHAPES & FORMS (Lessons 1-2)
  // ==========================================
  {
    id: 1,
    slug: 'mufridat',
    titleArabic: 'حُرُوف مُفْرَدَات',
    titleEnglish: 'Individual Letters (Mufridat)',
    stage: 1,
    stageTitle: 'Stage 1 · Letters & Forms',
    estimatedMinutes: 15,
    summary: 'Master the 29 individual Arabic letters with authentic Arabic phonetics, differentiating heavy (Musta’liyah) and whistle (Safeeriyah) letters.',
    keyRules: [
      'There are 29 individual Arabic letters (Mufridat).',
      'Pronounce with pure Arabic accent (e.g. بَ، تَ، ثَ — avoiding regional flattened vowels like Bay, Tay).',
      '7 Musta\'liyah Letters are ALWAYS heavy/thick: خ ، ص ، ض ، ط ، ظ ، غ ، ق (Grouped as خُصَّ ضَغْطٍ قِظْ).',
      '4 Letters are produced purely from the lips: ب ، م ، ف ، و.',
      '3 Safeeriyah letters create a sharp whistle-like sound: ز ، س ، ص.',
    ],
    pedagogicalTips: [
      'Focus on full mouth cavity resonance when practicing the 7 heavy letters.',
      'Keep the tongue tip just protruding between the teeth for ث, but behind the teeth for س.',
    ],
    tiles: [
      { id: 'l1-1', arabic: 'ا', transliteration: 'Alif', spelledArabic: 'أَلِف', ruleTag: 'normal' },
      { id: 'l1-2', arabic: 'ب', transliteration: 'Baa', spelledArabic: 'بَا', ruleTag: 'normal' },
      { id: 'l1-3', arabic: 'ت', transliteration: 'Taa', spelledArabic: 'تَا', ruleTag: 'normal' },
      { id: 'l1-4', arabic: 'ث', transliteration: 'Thaa', spelledArabic: 'ثَا', ruleTag: 'normal' },
      { id: 'l1-5', arabic: 'ج', transliteration: 'Jeem', spelledArabic: 'جِيم', ruleTag: 'normal' },
      { id: 'l1-6', arabic: 'ح', transliteration: 'Haa', spelledArabic: 'حَا', ruleTag: 'normal' },
      { id: 'l1-7', arabic: 'خ', transliteration: 'Khaa', spelledArabic: 'خَا', ruleTag: 'heavy', ruleNote: 'Musta’liyah (Heavy letter)' },
      { id: 'l1-8', arabic: 'د', transliteration: 'Daal', spelledArabic: 'دَال', ruleTag: 'normal' },
      { id: 'l1-9', arabic: 'ذ', transliteration: 'Dhaal', spelledArabic: 'ذَال', ruleTag: 'normal' },
      { id: 'l1-10', arabic: 'ر', transliteration: 'Raa', spelledArabic: 'رَا', ruleTag: 'normal' },
      { id: 'l1-11', arabic: 'ز', transliteration: 'Zaa', spelledArabic: 'زَاي', ruleTag: 'whistle', ruleNote: 'Safeeriyah (Whistling sound)' },
      { id: 'l1-12', arabic: 'س', transliteration: 'Seen', spelledArabic: 'سِين', ruleTag: 'whistle', ruleNote: 'Safeeriyah (Whistling sound)' },
      { id: 'l1-13', arabic: 'ش', transliteration: 'Sheen', spelledArabic: 'شِين', ruleTag: 'normal' },
      { id: 'l1-14', arabic: 'ص', transliteration: 'Saad', spelledArabic: 'صَاد', ruleTag: 'heavy', ruleNote: 'Musta’liyah & Safeeriyah' },
      { id: 'l1-15', arabic: 'ض', transliteration: 'Dhaad', spelledArabic: 'ضَاد', ruleTag: 'heavy', ruleNote: 'Musta’liyah (Heavy letter)' },
      { id: 'l1-16', arabic: 'ط', transliteration: 'Twa', spelledArabic: 'طَا', ruleTag: 'heavy', ruleNote: 'Musta’liyah (Heavy letter)' },
      { id: 'l1-17', arabic: 'ظ', transliteration: 'Zhaa', spelledArabic: 'ظَا', ruleTag: 'heavy', ruleNote: 'Musta’liyah (Heavy letter)' },
      { id: 'l1-18', arabic: 'ع', transliteration: '\'Ayn', spelledArabic: 'عَيْن', ruleTag: 'normal' },
      { id: 'l1-19', arabic: 'غ', transliteration: 'Ghayn', spelledArabic: 'غَيْن', ruleTag: 'heavy', ruleNote: 'Musta’liyah (Heavy letter)' },
      { id: 'l1-20', arabic: 'ف', transliteration: 'Faa', spelledArabic: 'فَا', ruleTag: 'normal' },
      { id: 'l1-21', arabic: 'ق', transliteration: 'Qaaf', spelledArabic: 'قَاف', ruleTag: 'heavy', ruleNote: 'Musta’liyah (Heavy letter)' },
      { id: 'l1-22', arabic: 'ك', transliteration: 'Kaaf', spelledArabic: 'كَاف', ruleTag: 'normal' },
      { id: 'l1-23', arabic: 'ل', transliteration: 'Laam', spelledArabic: 'لَام', ruleTag: 'normal' },
      { id: 'l1-24', arabic: 'م', transliteration: 'Meem', spelledArabic: 'مِيم', ruleTag: 'normal' },
      { id: 'l1-25', arabic: 'ن', transliteration: 'Noon', spelledArabic: 'نُون', ruleTag: 'normal' },
      { id: 'l1-26', arabic: 'و', transliteration: 'Waw', spelledArabic: 'وَاو', ruleTag: 'normal' },
      { id: 'l1-27', arabic: 'ه', transliteration: 'Haa (Soft)', spelledArabic: 'هَا', ruleTag: 'normal' },
      { id: 'l1-28', arabic: 'ء', transliteration: 'Hamzah', spelledArabic: 'هَمْزَة', ruleTag: 'normal' },
      { id: 'l1-29', arabic: 'ي', transliteration: 'Yaa', spelledArabic: 'يَا', ruleTag: 'normal' },
    ],
    quiz: [
      {
        question: 'Which of the following contains ONLY Musta\'liyah (Heavy) letters?',
        options: [
          { text: 'خ ، ص ، ض ، ط ، ظ ، غ ، ق', correct: true, explanation: 'Correct! The 7 heavy letters are grouped as خُصَّ ضَغْطٍ قِظْ.' },
          { text: 'ب ، ت ، ث ، ج ، ح', correct: false, explanation: 'These are standard light letters (Muraqqaqah).' },
          { text: 'ز ، س ، ص ، ش', correct: false, explanation: 'These are whistling/sibilant letters, only Saad is heavy.' },
        ],
      },
    ],
  },
  {
    id: 2,
    slug: 'murakkabat',
    titleArabic: 'حُرُوف مُرَكَّبَات',
    titleEnglish: 'Compound Letters (Murakkabat)',
    stage: 1,
    stageTitle: 'Stage 1 · Letters & Forms',
    estimatedMinutes: 20,
    summary: 'Recognize letters when joined in cursive script. Identify letter heads, bodies, and dot configurations.',
    keyRules: [
      'Two or more joined letters form a Murakkab (Compound).',
      'When letters join, the body is often omitted and only the head is written.',
      'Differentiate similar letter shapes by the count and position of dots (e.g. ب vs ت vs ث vs ن vs ي).',
    ],
    pedagogicalTips: [
      'Read each letter individually from right to left while recognizing cursive attachments.',
    ],
    tiles: [
      { id: 'l2-1', arabic: 'لَا', transliteration: 'Laam-Alif', spelledArabic: 'لَام أَلِف' },
      { id: 'l2-2', arabic: 'بَا', transliteration: 'Baa-Alif', spelledArabic: 'بَا أَلِف' },
      { id: 'l2-3', arabic: 'نَا', transliteration: 'Noon-Alif', spelledArabic: 'نُون أَلِف' },
      { id: 'l2-4', arabic: 'ثَا', transliteration: 'Thaa-Alif', spelledArabic: 'ثَا أَلِف' },
      { id: 'l2-5', arabic: 'يَا', transliteration: 'Yaa-Alif', spelledArabic: 'يَا أَلِف' },
      { id: 'l2-6', arabic: 'جَا', transliteration: 'Jeem-Alif', spelledArabic: 'جِيم أَلِف' },
      { id: 'l2-7', arabic: 'حَا', transliteration: 'Haa-Alif', spelledArabic: 'حَا أَلِف' },
      { id: 'l2-8', arabic: 'خَا', transliteration: 'Khaa-Alif', spelledArabic: 'خَا أَلِف' },
      { id: 'l2-9', arabic: 'سَا', transliteration: 'Seen-Alif', spelledArabic: 'سِين أَلِف' },
      { id: 'l2-10', arabic: 'شَا', transliteration: 'Sheen-Alif', spelledArabic: 'شِين أَلِف' },
      { id: 'l2-11', arabic: 'صَا', transliteration: 'Saad-Alif', spelledArabic: 'صَاد أَلِف' },
      { id: 'l2-12', arabic: 'ضَا', transliteration: 'Dhaad-Alif', spelledArabic: 'ضَاد أَلِف' },
      { id: 'l2-13', arabic: 'طَا', transliteration: 'Twa-Alif', spelledArabic: 'طَا أَلِف' },
      { id: 'l2-14', arabic: 'ظَا', transliteration: 'Zhaa-Alif', spelledArabic: 'ظَا أَلِف' },
      { id: 'l2-15', arabic: 'عَا', transliteration: 'Ayn-Alif', spelledArabic: 'عَيْن أَلِف' },
      { id: 'l2-16', arabic: 'غَا', transliteration: 'Ghayn-Alif', spelledArabic: 'غَيْن أَلِف' },
      { id: 'l2-17', arabic: 'فَا', transliteration: 'Faa-Alif', spelledArabic: 'فَا أَلِف' },
      { id: 'l2-18', arabic: 'قَا', transliteration: 'Qaaf-Alif', spelledArabic: 'قَاف أَلِف' },
      { id: 'l2-19', arabic: 'كَا', transliteration: 'Kaaf-Alif', spelledArabic: 'كَاف أَلِف' },
      { id: 'l2-20', arabic: 'هَا', transliteration: 'Haa-Alif', spelledArabic: 'هَا أَلِف' },
      { id: 'l2-21', arabic: 'لَب', transliteration: 'Laam-Baa', spelledArabic: 'لَام بَا' },
      { id: 'l2-22', arabic: 'كَب', transliteration: 'Kaaf-Baa', spelledArabic: 'كَاف بَا' },
      { id: 'l2-23', arabic: 'كَت', transliteration: 'Kaaf-Taa', spelledArabic: 'كَاف تَا' },
      { id: 'l2-24', arabic: 'سَل', transliteration: 'Seen-Laam', spelledArabic: 'سِين لَام' },
      { id: 'l2-25', arabic: 'بَلَغ', transliteration: 'Baa-Laam-Ghayn', spelledArabic: 'بَا لَام غَيْن' },
      { id: 'l2-26', arabic: 'خَلَق', transliteration: 'Khaa-Laam-Qaaf', spelledArabic: 'خَا لَام قَاف' },
      { id: 'l2-27', arabic: 'نَصَر', transliteration: 'Noon-Saad-Raa', spelledArabic: 'نُون صَاد رَا' },
      { id: 'l2-28', arabic: 'فَتَح', transliteration: 'Faa-Taa-Haa', spelledArabic: 'فَا تَا حَا' },
    ],
  },

  // ==========================================
  // STAGE 2: VOWELS & MOVEMENT (Lessons 3-6)
  // ==========================================
  {
    id: 3,
    slug: 'harakaat',
    titleArabic: 'الْحَرَكَات',
    titleEnglish: 'Short Vowels (Harakaat)',
    stage: 2,
    stageTitle: 'Stage 2 · Vowels & Movement',
    estimatedMinutes: 18,
    summary: 'Master the 3 short vowels (Fathah, Kasrah, Dammah). Learn to pronounce without stretching or jerking the voice.',
    keyRules: [
      'Fathah (َ) placed on top, Kasrah (ِ) placed underneath, Dammah (ُ) placed on top.',
      'Pronounce Fathah by opening the mouth and raising the voice.',
      'Pronounce Kasrah by dropping the jaw, and Dammah by rounding the lips.',
      'A letter with a Harakah is called Mutaharrik(ah). Do NOT stretch Harakaat.',
      'If Alif carries a Harakah or Sukoon, it becomes a Hamzah (أَ ، إِ ، أُ).',
    ],
    pedagogicalTips: [
      'Maintain crisp, single-count duration for every vowel.',
    ],
    tiles: [
      { id: 'l3-1', arabic: 'أَ', transliteration: 'A', spelledArabic: 'هَمْزَة فَتْحَة أَ' },
      { id: 'l3-2', arabic: 'إِ', transliteration: 'I', spelledArabic: 'هَمْزَة كَسْرَة إِ' },
      { id: 'l3-3', arabic: 'أُ', transliteration: 'U', spelledArabic: 'هَمْزَة ضَمَّة أُ' },
      { id: 'l3-4', arabic: 'بَ', transliteration: 'Ba', spelledArabic: 'بَا فَتْحَة بَ' },
      { id: 'l3-5', arabic: 'بِ', transliteration: 'Bi', spelledArabic: 'بَا كَسْرَة بِ' },
      { id: 'l3-6', arabic: 'بُ', transliteration: 'Bu', spelledArabic: 'بَا ضَمَّة بُ' },
      { id: 'l3-7', arabic: 'تَ', transliteration: 'Ta', spelledArabic: 'تَا فَتْحَة تَ' },
      { id: 'l3-8', arabic: 'تِ', transliteration: 'Ti', spelledArabic: 'تَا كَسْرَة تِ' },
      { id: 'l3-9', arabic: 'تُ', transliteration: 'Tu', spelledArabic: 'تَا ضَمَّة تُ' },
      { id: 'l3-10', arabic: 'ثَ', transliteration: 'Tha', spelledArabic: 'ثَا فَتْحَة ثَ' },
      { id: 'l3-11', arabic: 'ثِ', transliteration: 'Thi', spelledArabic: 'ثَا كَسْرَة ثِ' },
      { id: 'l3-12', arabic: 'ثُ', transliteration: 'Thu', spelledArabic: 'ثَا ضَمَّة ثُ' },
      { id: 'l3-13', arabic: 'جَ', transliteration: 'Ja', spelledArabic: 'جِيم فَتْحَة جَ' },
      { id: 'l3-14', arabic: 'جِ', transliteration: 'Ji', spelledArabic: 'جِيم كَسْرَة جِ' },
      { id: 'l3-15', arabic: 'جُ', transliteration: 'Ju', spelledArabic: 'جِيم ضَمَّة جُ' },
      { id: 'l3-16', arabic: 'حَ', transliteration: 'Ha', spelledArabic: 'حَا فَتْحَة حَ' },
      { id: 'l3-17', arabic: 'حِ', transliteration: 'Hi', spelledArabic: 'حَا كَسْرَة حِ' },
      { id: 'l3-18', arabic: 'حُ', transliteration: 'Hu', spelledArabic: 'حَا ضَمَّة حُ' },
      { id: 'l3-19', arabic: 'خَ', transliteration: 'Kha', spelledArabic: 'خَا فَتْحَة خَ', ruleTag: 'heavy' },
      { id: 'l3-20', arabic: 'خِ', transliteration: 'Khi', spelledArabic: 'خَا كَسْرَة خِ', ruleTag: 'heavy' },
      { id: 'l3-21', arabic: 'خُ', transliteration: 'Khu', spelledArabic: 'خَا ضَمَّة خُ', ruleTag: 'heavy' },
      { id: 'l3-22', arabic: 'رَ', transliteration: 'Ra (Heavy)', spelledArabic: 'رَا فَتْحَة رَ', ruleTag: 'heavy' },
      { id: 'l3-23', arabic: 'رِ', transliteration: 'Ri (Light)', spelledArabic: 'رَا كَسْرَة رِ', ruleTag: 'normal' },
      { id: 'l3-24', arabic: 'رُ', transliteration: 'Ru (Heavy)', spelledArabic: 'رَا ضَمَّة رُ', ruleTag: 'heavy' },
    ],
  },
  {
    id: 4,
    slug: 'similar-letters',
    titleArabic: 'تَمْيِيزُ الْحُرُوف الْمُتَشَابِهَة',
    titleEnglish: 'Similar Sounding Letters',
    stage: 2,
    stageTitle: 'Stage 2 · Vowels & Movement',
    estimatedMinutes: 20,
    summary: 'Side-by-side contrast drills differentiating confusing letter pairs (Taa vs Twa, Zaa vs Dhal vs Zhaa, Saad vs Seen, etc.).',
    keyRules: [
      'Read in Rawan (fluent) mode without spelling breakdown.',
      'Differentiate clearly between light pairs and heavy/deep counterparts.',
      'Failing to distinguish these alters the meaning and invalidates recitation in Salah.',
    ],
    pedagogicalTips: [
      'Compare تَ (light incisor tip) against طَ (heavy palate contact).',
      'Compare زَ (whistling) against ذَ (soft interdental) against ظَ (heavy interdental).',
    ],
    tiles: [
      { id: 'l4-1', arabic: 'تَ تِ تُ', transliteration: 'Ta Ti Tu (Light)', ruleTag: 'normal' },
      { id: 'l4-2', arabic: 'طَ طِ طُ', transliteration: 'Twa Twi Twu (Heavy)', ruleTag: 'heavy' },
      { id: 'l4-3', arabic: 'زَ زِ زُ', transliteration: 'Za Zi Zu (Whistle)', ruleTag: 'whistle' },
      { id: 'l4-4', arabic: 'ذَ ذِ ذُ', transliteration: 'Dha Dhi Dhu (Soft)', ruleTag: 'normal' },
      { id: 'l4-5', arabic: 'ظَ ظِ ظُ', transliteration: 'Zha Zhi Zhu (Heavy)', ruleTag: 'heavy' },
      { id: 'l4-6', arabic: 'ضَ ضِ ضُ', transliteration: 'Dha Dhi Dhu (Lateral)', ruleTag: 'heavy' },
      { id: 'l4-7', arabic: 'ثَ ثِ ثُ', transliteration: 'Tha Thi Thu (Soft Tip)', ruleTag: 'normal' },
      { id: 'l4-8', arabic: 'سَ سِ سُ', transliteration: 'Sa Si Su (Whistle)', ruleTag: 'whistle' },
      { id: 'l4-9', arabic: 'صَ صِ صُ', transliteration: 'Saad (Heavy Whistle)', ruleTag: 'heavy' },
      { id: 'l4-10', arabic: 'كَ كِ كُ', transliteration: 'Ka Ki Ku (Light Palate)', ruleTag: 'normal' },
      { id: 'l4-11', arabic: 'قَ قِ قُ', transliteration: 'Qa Qi Qu (Heavy Uvular)', ruleTag: 'heavy' },
      { id: 'l4-12', arabic: 'حَ حِ حُ', transliteration: 'Ha Hi Hu (Middle Throat)', ruleTag: 'normal' },
      { id: 'l4-13', arabic: 'هَ هِ هُ', transliteration: 'Ha Hi Hu (Bottom Throat)', ruleTag: 'normal' },
      { id: 'l4-14', arabic: 'عَ عِ عُ', transliteration: '\'A \'I \'U (Pharynx)', ruleTag: 'normal' },
      { id: 'l4-15', arabic: 'أَ إِ أُ', transliteration: 'A I U (Glottal Hamzah)', ruleTag: 'normal' },
    ],
  },
  {
    id: 5,
    slug: 'tanween',
    titleArabic: 'التَّنْوِين',
    titleEnglish: 'Tanween (Double Vowels)',
    stage: 2,
    stageTitle: 'Stage 2 · Vowels & Movement',
    estimatedMinutes: 20,
    summary: 'Double Fathah (ً), Double Kasrah (ٍ), and Double Dammah (ٌ). Understanding that Tanween is an unwritten Noon Saakinah.',
    keyRules: [
      'Fathatayn (ً), Kasratayn (ٍ), and Dammatayn (ٌ) are called Tanween.',
      'A letter with Tanween is called Munawwan.',
      'Tanween produces the sound of a Noon Saakin at the end of a word (e.g. أَنْ = أَنٍ).',
      'When an Alif appears after Fathatayn (e.g. بًا), do not pronounce the Alif during continuous reading.',
    ],
    pedagogicalTips: [
      'Spell out: مً $\to$ Meem Two Fathah $\to$ Man.',
    ],
    tiles: [
      { id: 'l5-1', arabic: 'تًا', transliteration: 'Tan', spelledArabic: 'تَا فَتْحَتَيْن تًا' },
      { id: 'l5-2', arabic: 'تٍ', transliteration: 'Tin', spelledArabic: 'تَا كَسْرَتَيْن تٍ' },
      { id: 'l5-3', arabic: 'تٌ', transliteration: 'Tun', spelledArabic: 'تَا ضَمَّتَيْن تٌ' },
      { id: 'l5-4', arabic: 'طًا', transliteration: 'Twan (Heavy)', ruleTag: 'heavy' },
      { id: 'l5-5', arabic: 'طٍ', transliteration: 'Twin (Heavy)', ruleTag: 'heavy' },
      { id: 'l5-6', arabic: 'طٌ', transliteration: 'Twun (Heavy)', ruleTag: 'heavy' },
      { id: 'l5-7', arabic: 'زًا', transliteration: 'Zan', ruleTag: 'whistle' },
      { id: 'l5-8', arabic: 'زٍ', transliteration: 'Zin', ruleTag: 'whistle' },
      { id: 'l5-9', arabic: 'زٌ', transliteration: 'Zun', ruleTag: 'whistle' },
      { id: 'l5-10', arabic: 'صًا', transliteration: 'Saan (Heavy)', ruleTag: 'heavy' },
      { id: 'l5-11', arabic: 'صٍ', transliteration: 'Seen (Heavy)', ruleTag: 'heavy' },
      { id: 'l5-12', arabic: 'صٌ', transliteration: 'Soon (Heavy)', ruleTag: 'heavy' },
      { id: 'l5-13', arabic: 'قًا', transliteration: 'Qan (Heavy)', ruleTag: 'heavy' },
      { id: 'l5-14', arabic: 'قٍ', transliteration: 'Qin (Heavy)', ruleTag: 'heavy' },
      { id: 'l5-15', arabic: 'قٌ', transliteration: 'Qun (Heavy)', ruleTag: 'heavy' },
      { id: 'l5-16', arabic: 'عًا', transliteration: '\'An', ruleTag: 'normal' },
      { id: 'l5-17', arabic: 'عٍ', transliteration: '\'In', ruleTag: 'normal' },
      { id: 'l5-18', arabic: 'عٌ', transliteration: '\'Un', ruleTag: 'normal' },
    ],
  },
  {
    id: 6,
    slug: 'word-exercises-1',
    titleArabic: 'تَمَارِين الْحَرَكَات وَالتَّنْوِين',
    titleEnglish: 'Word Reading Exercises (Vowels & Tanween)',
    stage: 2,
    stageTitle: 'Stage 2 · Vowels & Movement',
    estimatedMinutes: 25,
    summary: 'Practice multi-letter words combining Harakaat and Tanween. Master both Hijjay (spelling) and Rawan (fluent) reading.',
    keyRules: [
      'Read both ways: Rawan (fluent whole-word) and Hijjay (letter-by-letter spelling).',
      'Pay strict attention to Musta\'liyah heavy letters within multi-syllable words.',
      'Do not drag short vowels beyond 1 count.',
    ],
    pedagogicalTips: [
      'Spelling example for مَلِكٌ: Meem Fathah Ma, Laam Kasrah Li $\to$ Mali, Kaaf Dammatayn Kun $\to$ Malikun.',
    ],
    tiles: [
      { id: 'l6-1', arabic: 'نَزَلَ', transliteration: 'Nazala', englishMeaning: 'He descended' },
      { id: 'l6-2', arabic: 'خَلَقَ', transliteration: 'Khalaqa', ruleTag: 'heavy', englishMeaning: 'He created' },
      { id: 'l6-3', arabic: 'صَدَقَ', transliteration: 'Sadaqa', ruleTag: 'heavy', englishMeaning: 'He spoke truth' },
      { id: 'l6-4', arabic: 'بَلَغَ', transliteration: 'Balagha', ruleTag: 'heavy', englishMeaning: 'He reached' },
      { id: 'l6-5', arabic: 'جَعَلَ', transliteration: 'Ja\'ala', englishMeaning: 'He made' },
      { id: 'l6-6', arabic: 'رُسُلٌ', transliteration: 'Rusulun', englishMeaning: 'Messengers' },
      { id: 'l6-7', arabic: 'صُحُفٌ', transliteration: 'Suhufun', ruleTag: 'heavy', englishMeaning: 'Pages / Scriptures' },
      { id: 'l6-8', arabic: 'حَمِدَ', transliteration: 'Hamida', englishMeaning: 'He praised' },
      { id: 'l6-9', arabic: 'مَلِكٌ', transliteration: 'Malikun', englishMeaning: 'King' },
      { id: 'l6-10', arabic: 'أَحَدًا', transliteration: 'Ahadan', englishMeaning: 'One / Anyone' },
      { id: 'l6-11', arabic: 'مَرَضًا', transliteration: 'Maradan', ruleTag: 'heavy', englishMeaning: 'A disease' },
      { id: 'l6-12', arabic: 'عَلَقَةٍ', transliteration: '\'Alaqatin', ruleTag: 'heavy', englishMeaning: 'A clinging clot' },
      { id: 'l6-13', arabic: 'سَفَرَةٍ', transliteration: 'Safaratin', englishMeaning: 'Scribes' },
      { id: 'l6-14', arabic: 'شَجَرَةٍ', transliteration: 'Shajaratin', englishMeaning: 'A tree' },
    ],
  },

  // ==========================================
  // STAGE 3: PROLONGATION & SILENCE (Lessons 7-11)
  // ==========================================
  {
    id: 7,
    slug: 'maddah-letters',
    titleArabic: 'حُرُوفُ الْمَدَّة',
    titleEnglish: 'Letters of Maddah (Long Vowels)',
    stage: 3,
    stageTitle: 'Stage 3 · Prolongation & Silence',
    estimatedMinutes: 20,
    summary: 'The 3 Maddah letters (Alif preceded by Fathah, Waw Saakin preceded by Dammah, Yaa Saakin preceded by Kasrah). Stretch for exactly 2 Harakaat (1 Alif).',
    keyRules: [
      'Alif Maddah: Alif preceded by Fathah (بَا).',
      'Waw Maddah: Waw Saakin preceded by Dammah (بُو).',
      'Yaa Maddah: Yaa Saakin preceded by Kasrah (بِي).',
      'Stretch these letters for exactly 2 counts (1 Alif) from the Jawf (empty mouth cavity).',
    ],
    pedagogicalTips: [
      'Keep vowel duration uniform across all three types.',
    ],
    tiles: [
      { id: 'l7-1', arabic: 'بَا', transliteration: 'Baa', ruleTag: 'madd' },
      { id: 'l7-2', arabic: 'بُو', transliteration: 'Boo', ruleTag: 'madd' },
      { id: 'l7-3', arabic: 'بِي', transliteration: 'Bee', ruleTag: 'madd' },
      { id: 'l7-4', arabic: 'تَا', transliteration: 'Taa', ruleTag: 'madd' },
      { id: 'l7-5', arabic: 'تُو', transliteration: 'Too', ruleTag: 'madd' },
      { id: 'l7-6', arabic: 'تِي', transliteration: 'Tee', ruleTag: 'madd' },
      { id: 'l7-7', arabic: 'خَا', transliteration: 'Khaa (Heavy)', ruleTag: 'heavy' },
      { id: 'l7-8', arabic: 'خُو', transliteration: 'Khoo (Heavy)', ruleTag: 'heavy' },
      { id: 'l7-9', arabic: 'خِي', transliteration: 'Khee (Heavy)', ruleTag: 'heavy' },
      { id: 'l7-10', arabic: 'طَا', transliteration: 'Twaa (Heavy)', ruleTag: 'heavy' },
      { id: 'l7-11', arabic: 'طُو', transliteration: 'Twoo (Heavy)', ruleTag: 'heavy' },
      { id: 'l7-12', arabic: 'طِي', transliteration: 'Twee (Heavy)', ruleTag: 'heavy' },
      { id: 'l7-13', arabic: 'قَا', transliteration: 'Qaa (Heavy)', ruleTag: 'heavy' },
      { id: 'l7-14', arabic: 'قُو', transliteration: 'Qoo (Heavy)', ruleTag: 'heavy' },
      { id: 'l7-15', arabic: 'قِي', transliteration: 'Qee (Heavy)', ruleTag: 'heavy' },
    ],
  },
  {
    id: 8,
    slug: 'standing-harakaat',
    titleArabic: 'الْحَرَكَات الْقَائِمَة',
    titleEnglish: 'Vertical / Standing Harakaat',
    stage: 3,
    stageTitle: 'Stage 3 · Prolongation & Silence',
    estimatedMinutes: 20,
    summary: 'Standing Fathah (Khara Zabar), Standing Kasrah (Khari Zayr), and Inverted Dammah (Ulta Paysh). Equal in length to Letters of Maddah (2 counts).',
    keyRules: [
      'Standing Fathah (ﹳ) = Alif Maddah.',
      'Standing Kasrah (ﹶ) = Yaa Maddah.',
      'Inverted Dammah (ﹸ) = Waw Maddah.',
      'Stretch for 2 counts (1 Alif).',
    ],
    pedagogicalTips: [
      'Practice with similar sounding pairs to reinforce distinction during vowel elongation.',
    ],
    tiles: [
      { id: 'l8-1', arabic: 'تٰ', transliteration: 'Taa (Standing)', ruleTag: 'madd' },
      { id: 'l8-2', arabic: 'تٖ', transliteration: 'Tee (Standing)', ruleTag: 'madd' },
      { id: 'l8-3', arabic: 'تٗ', transliteration: 'Too (Inverted)', ruleTag: 'madd' },
      { id: 'l8-4', arabic: 'طٰ', transliteration: 'Twaa (Heavy Standing)', ruleTag: 'heavy' },
      { id: 'l8-5', arabic: 'طٖ', transliteration: 'Twee (Heavy Standing)', ruleTag: 'heavy' },
      { id: 'l8-6', arabic: 'طٗ', transliteration: 'Twoo (Heavy Inverted)', ruleTag: 'heavy' },
      { id: 'l8-7', arabic: 'هٰذَا', transliteration: 'Haadhaa', ruleTag: 'madd' },
      { id: 'l8-8', arabic: 'ذٰلِكَ', transliteration: 'Dhaalika', ruleTag: 'madd' },
      { id: 'l8-9', arabic: 'لَهٗ', transliteration: 'Lahoo', ruleTag: 'madd' },
      { id: 'l8-10', arabic: 'بِهٖ', transliteration: 'Bihee', ruleTag: 'madd' },
    ],
  },
  {
    id: 9,
    slug: 'leen-letters',
    titleArabic: 'حُرُوفُ اللِّين',
    titleEnglish: 'Letters of Leen (Soft Vowels)',
    stage: 3,
    stageTitle: 'Stage 3 · Prolongation & Silence',
    estimatedMinutes: 20,
    summary: 'The 2 Leen letters: Waw Saakin preceded by Fathah (َ + ْو) and Yaa Saakin preceded by Fathah (َ + ْي). Pronounced smoothly and softly without jerking.',
    keyRules: [
      'Waw Leen: Fathah before Waw Saakin (خَوْ).',
      'Yaa Leen: Fathah before Yaa Saakin (خَيْ).',
      'Pronounce softly (Leen = soft) without stretching during normal reading.',
    ],
    pedagogicalTips: [
      'Do not stretch like Madd letters during continuous reading.',
    ],
    tiles: [
      { id: 'l9-1', arabic: 'بَوْ', transliteration: 'Baw', ruleTag: 'leen' },
      { id: 'l9-2', arabic: 'بَيْ', transliteration: 'Bay', ruleTag: 'leen' },
      { id: 'l9-3', arabic: 'تَوْ', transliteration: 'Taw', ruleTag: 'leen' },
      { id: 'l9-4', arabic: 'تَيْ', transliteration: 'Tay', ruleTag: 'leen' },
      { id: 'l9-5', arabic: 'خَوْ', transliteration: 'Khaw (Heavy)', ruleTag: 'heavy' },
      { id: 'l9-6', arabic: 'خَيْ', transliteration: 'Khay (Heavy)', ruleTag: 'heavy' },
      { id: 'l9-7', arabic: 'صَوْ', transliteration: 'Saw (Heavy)', ruleTag: 'heavy' },
      { id: 'l9-8', arabic: 'صَيْ', transliteration: 'Say (Heavy)', ruleTag: 'heavy' },
      { id: 'l9-9', arabic: 'قَوْ', transliteration: 'Qaw (Heavy)', ruleTag: 'heavy' },
      { id: 'l9-10', arabic: 'قَيْ', transliteration: 'Qay (Heavy)', ruleTag: 'heavy' },
      { id: 'l9-11', arabic: 'يَوْمَ', transliteration: 'Yawma', ruleTag: 'leen' },
      { id: 'l9-12', arabic: 'خَوْفٌ', transliteration: 'Khawfun', ruleTag: 'leen' },
      { id: 'l9-13', arabic: 'قُرَيْشٍ', transliteration: 'Quraysh', ruleTag: 'leen' },
      { id: 'l9-14', arabic: 'لَيْسَ', transliteration: 'Laysa', ruleTag: 'leen' },
    ],
  },
  {
    id: 10,
    slug: 'word-exercises-2',
    titleArabic: 'تَمْرِينُ الْمَدِّ وَاللِّين',
    titleEnglish: 'Combined Maddah & Leen Quranic Drills',
    stage: 3,
    stageTitle: 'Stage 3 · Prolongation & Silence',
    estimatedMinutes: 25,
    summary: 'Comprehensive multi-syllable Quranic words integrating Harakaat, Tanween, Standing Vowels, Madd letters, and Leen letters.',
    keyRules: [
      'Combines all rules from Lessons 1 to 9.',
      'Practice joined spelling (Hijjay) and flowing recitation (Rawan).',
    ],
    pedagogicalTips: [
      'Pay close attention to words like نُوحِيهَا which contain all 3 Madd letters in one word.',
    ],
    tiles: [
      { id: 'l10-1', arabic: 'قَالَ', transliteration: 'Qaala', ruleTag: 'madd' },
      { id: 'l10-2', arabic: 'صِرَاطَ', transliteration: 'Siraata', ruleTag: 'heavy' },
      { id: 'l10-3', arabic: 'كَانُوا', transliteration: 'Kaanoo', ruleTag: 'madd' },
      { id: 'l10-4', arabic: 'قَالُوا', transliteration: 'Qaaloo', ruleTag: 'madd' },
      { id: 'l10-5', arabic: 'سَوْفَ', transliteration: 'Sawfa', ruleTag: 'leen' },
      { id: 'l10-6', arabic: 'قَوْلٌ', transliteration: 'Qawlun', ruleTag: 'leen' },
      { id: 'l10-7', arabic: 'فِيهِ', transliteration: 'Feehi', ruleTag: 'madd' },
      { id: 'l10-8', arabic: 'عَذَابًا', transliteration: '\'Adhaaban', ruleTag: 'madd' },
      { id: 'l10-9', arabic: 'غَفُورًا', transliteration: 'Ghafooran', ruleTag: 'heavy' },
      { id: 'l10-10', arabic: 'شَكُورًا', transliteration: 'Shakooran', ruleTag: 'madd' },
      { id: 'l10-11', arabic: 'نُوحِيهَا', transliteration: 'Nooheehaa (All 3 Madd)', ruleTag: 'madd' },
      { id: 'l10-12', arabic: 'يَوْمَئِذٍ', transliteration: 'Yawma\'idhin', ruleTag: 'leen' },
      { id: 'l10-13', arabic: 'مَوْعِظَةٌ', transliteration: 'Maw\'idhatun', ruleTag: 'leen' },
      { id: 'l10-14', arabic: 'عَزِيزٌ', transliteration: '\'Azeezun', ruleTag: 'madd' },
    ],
  },
  {
    id: 11,
    slug: 'sukoon-qalqala',
    titleArabic: 'السُّكُون وَالْقَلْقَلَة',
    titleEnglish: 'Sukoon (Jazm) & Qalqala (Echo)',
    stage: 3,
    stageTitle: 'Stage 3 · Prolongation & Silence',
    estimatedMinutes: 25,
    summary: 'The Sukoon sign (ْ). Connecting silent letters to preceding vowels, Hamzah Saakinah abrupt stop, and the 5 Qalqala echo letters (قُطْبُ جَدٍ).',
    keyRules: [
      'A letter with Sukoon (ْ) is called Saakin(ah) and is read joined to the preceding letter.',
      'Hamzah Saakinah (أْ / إْ) MUST be pronounced with an abrupt, clean glottal stop.',
      '5 Letters of Qalqala: ق ، ط ، ب ، ج ، د (Combined as قُطْبُ جَدٍ).',
      'Qalqala means bouncing/echoing the sound when these letters are Saakin.',
    ],
    pedagogicalTips: [
      'Ensure the echo in Qalqala does not sound like a full vowel (Fathah/Kasrah/Dammah).',
    ],
    tiles: [
      { id: 'l11-1', arabic: 'أَقْ', transliteration: 'Aq (Echo)', ruleTag: 'echo', targetLetter: 'ق' },
      { id: 'l11-2', arabic: 'أَطْ', transliteration: 'At (Echo)', ruleTag: 'echo', targetLetter: 'ط' },
      { id: 'l11-3', arabic: 'أَبْ', transliteration: 'Ab (Echo)', ruleTag: 'echo', targetLetter: 'ب' },
      { id: 'l11-4', arabic: 'أَجْ', transliteration: 'Aj (Echo)', ruleTag: 'echo', targetLetter: 'ج' },
      { id: 'l11-5', arabic: 'أَدْ', transliteration: 'Ad (Echo)', ruleTag: 'echo', targetLetter: 'د' },
      { id: 'l11-6', arabic: 'قُلْ', transliteration: 'Qul', ruleTag: 'normal' },
      { id: 'l11-7', arabic: 'مَنْ', transliteration: 'Man', ruleTag: 'normal' },
      { id: 'l11-8', arabic: 'قَدْ', transliteration: 'Qad (Qalqala)', ruleTag: 'echo' },
      { id: 'l11-9', arabic: 'ذُقْ', transliteration: 'Dhuq (Qalqala)', ruleTag: 'echo' },
      { id: 'l11-10', arabic: 'يَجْعَلْ', transliteration: 'Yaj\'al', ruleTag: 'echo' },
      { id: 'l11-11', arabic: 'يُؤْمِنُونَ', transliteration: 'Yu\'minoona (Abrupt Hamzah)', ruleTag: 'normal' },
      { id: 'l11-12', arabic: 'إِقْرَأْ', transliteration: 'Iqra\' (Qalqala + Hamzah stop)', ruleTag: 'echo' },
      { id: 'l11-13', arabic: 'أَبْوَابًا', transliteration: 'Abwaaban (Qalqala)', ruleTag: 'echo' },
      { id: 'l11-14', arabic: 'تَجْرِي', transliteration: 'Tajree (Qalqala)', ruleTag: 'echo' },
    ],
  },

  // ==========================================
  // STAGE 4: RECITATION RULES & FLUENCY (Lessons 12-22)
  // ==========================================
  {
    id: 12,
    slug: 'noon-saakin-izhar-ikhfa',
    titleArabic: 'نُون سَاكِنَة وَتَنْوِين: إِظْهَار وَإِخْفَاء',
    titleEnglish: 'Noon Saakin & Tanween: Izhar & Ikhfa',
    stage: 4,
    stageTitle: 'Stage 4 · Recitation Rules & Fluency',
    estimatedMinutes: 25,
    summary: 'Izhar (clear pronunciation without Ghunnah before 6 throat letters) and Ikhfa (concealment with Ghunnah before 15 letters).',
    keyRules: [
      'Izhar: If any of the 6 Throat letters (ء ، هـ ، ع ، ح ، غ ، خ) follows Noon Saakin or Tanween, pronounce clearly without Ghunnah.',
      'Ikhfa: If any of the 15 Ikhfa letters (ت ث ج د ذ ز س ش ص ض ط ظ ف ق ك) follows, conceal the Noon sound with 2 counts of Ghunnah.',
    ],
    pedagogicalTips: [
      'In Ikhfa, position your tongue near the exit point of the upcoming letter while nasalizing.',
    ],
    tiles: [
      { id: 'l12-1', arabic: 'مَنْ أَجَلٍ', transliteration: 'Man Ajalin (Izhar ء)', ruleTag: 'normal' },
      { id: 'l12-2', arabic: 'مَنْ هَادٍ', transliteration: 'Man Haadin (Izhar هـ)', ruleTag: 'normal' },
      { id: 'l12-3', arabic: 'مَنْ عَلَقٍ', transliteration: 'Man \'Alaqin (Izhar ع)', ruleTag: 'normal' },
      { id: 'l12-4', arabic: 'مَنْ حَكِيمٍ', transliteration: 'Man Hakeemin (Izhar ح)', ruleTag: 'normal' },
      { id: 'l12-5', arabic: 'مَنْ غَفُورٍ', transliteration: 'Man Ghafoorin (Izhar غ)', ruleTag: 'heavy' },
      { id: 'l12-6', arabic: 'مَنْ خَوْفٍ', transliteration: 'Man Khawfin (Izhar خ)', ruleTag: 'heavy' },
      { id: 'l12-7', arabic: 'مِنْ جُوعٍ', transliteration: 'Min Joo\'in (Ikhfa ج)', ruleTag: 'nasal' },
      { id: 'l12-8', arabic: 'مِنْ دُونِكُمْ', transliteration: 'Min Doonikum (Ikhfa د)', ruleTag: 'nasal' },
      { id: 'l12-9', arabic: 'مِنْ قَبْلُ', transliteration: 'Min Qablu (Heavy Ikhfa ق)', ruleTag: 'nasal' },
      { id: 'l12-10', arabic: 'عَذَابًا أَلِيمًا', transliteration: '\'Adhaaban Aleema (Izhar)', ruleTag: 'normal' },
      { id: 'l12-11', arabic: 'قَوْلًا ثَقِيلًا', transliteration: 'Qawlan Thaqeela (Ikhfa)', ruleTag: 'nasal' },
      { id: 'l12-12', arabic: 'سَمِيعٌ عَلِيمٌ', transliteration: 'Samee\'un \'Aleem (Izhar)', ruleTag: 'normal' },
    ],
  },
  {
    id: 13,
    slug: 'tashdeed',
    titleArabic: 'التَّشْدِيد',
    titleEnglish: 'Tashdeed (Shaddah) & Mushaddadah Letters',
    stage: 4,
    stageTitle: 'Stage 4 · Recitation Rules & Fluency',
    estimatedMinutes: 25,
    summary: 'The W-shaped Shaddah sign (ّ). Pronouncing doubled letters with slight holding, mandatory Ghunnah on Noon & Meem Mushaddadah (نّ ، مّ).',
    keyRules: [
      'A Mushaddadah letter is pronounced twice: first joining with the preceding vowel, then with its own vowel.',
      'Ghunnah (2-count nasalization) is MANDATORY on Noon Mushaddadah (نّ) and Meem Mushaddadah (مّ).',
      'When Qalqala letters have a Tashdeed (e.g. فِي الْحَجِّ), pronounce with emphatic explosive release on stop.',
    ],
    pedagogicalTips: [
      'Do not rush through نّ or مّ; hold the nasal resonance for full 2 counts.',
    ],
    tiles: [
      { id: 'l13-1', arabic: 'إِنَّ', transliteration: 'Inna', ruleTag: 'nasal', ruleNote: 'Noon Mushaddadah Ghunnah' },
      { id: 'l13-2', arabic: 'ثُمَّ', transliteration: 'Thumma', ruleTag: 'nasal', ruleNote: 'Meem Mushaddadah Ghunnah' },
      { id: 'l13-3', arabic: 'رَبِّ', transliteration: 'Rabbi', ruleTag: 'shaddah' },
      { id: 'l13-4', arabic: 'حَبِّ', transliteration: 'Habbi', ruleTag: 'shaddah' },
      { id: 'l13-5', arabic: 'فِي الْحَجِّ', transliteration: 'Fil-Hajj', ruleTag: 'echo', ruleNote: 'Strong Qalqala on stop' },
      { id: 'l13-6', arabic: 'الرَّحْمٰن', transliteration: 'Ar-Rahmaan', ruleTag: 'shaddah' },
      { id: 'l13-7', arabic: 'وَالشَّمْسِ', transliteration: 'Wash-Shamsi', ruleTag: 'shaddah' },
      { id: 'l13-8', arabic: 'وَالصَّالِحِينَ', transliteration: 'Was-Saaliheen', ruleTag: 'heavy' },
      { id: 'l13-9', arabic: 'وَالضُّحَى', transliteration: 'Wad-Duhaa', ruleTag: 'heavy' },
      { id: 'l13-10', arabic: 'جَنَّاتٍ', transliteration: 'Jannaatin', ruleTag: 'nasal' },
      { id: 'l13-11', arabic: 'عَبَدْتُّمْ', transliteration: '\'Abattum (Assimilation)', ruleTag: 'shaddah' },
    ],
  },
  {
    id: 14,
    slug: 'noon-saakin-idgham-iqlab',
    titleArabic: 'نُون سَاكِنَة وَتَنْوِين: إِدْغَام وَإِقْلَاب',
    titleEnglish: 'Noon Saakin & Tanween: Idgham & Iqlaab',
    stage: 4,
    stageTitle: 'Stage 4 · Recitation Rules & Fluency',
    estimatedMinutes: 25,
    summary: 'Idgham with Ghunnah (ي ن م و), Idgham without Ghunnah (ل ر), and Iqlaab (converting Noon to Meem before Baa).',
    keyRules: [
      'Idgham with Ghunnah: When followed by ي ، ن ، م ، و (Letters of Yanmoo), merge with 2-count nasal resonance.',
      'Idgham without Ghunnah: When followed by ل or ر, merge completely without nasalization.',
      'Iqlaab: When followed by ب, turn the Noon Saakin/Tanween into a soft Meem with Ghunnah.',
    ],
    pedagogicalTips: [
      'In Iqlaab (مِنْ بَعْدِ $\to$ Mim-ba\'di), close lips gently without pressing hard.',
    ],
    tiles: [
      { id: 'l14-1', arabic: 'مَنْ يَقُولُ', transliteration: 'May-Yaqoolu (Idgham + Ghunnah)', ruleTag: 'nasal' },
      { id: 'l14-2', arabic: 'مَنْ وَلِيٍّ', transliteration: 'Maw-Waliyyin (Idgham + Ghunnah)', ruleTag: 'nasal' },
      { id: 'l14-3', arabic: 'مِنْ مَّالٍ', transliteration: 'Mim-Maalin (Idgham + Ghunnah)', ruleTag: 'nasal' },
      { id: 'l14-4', arabic: 'مِنْ نَّصِيرٍ', transliteration: 'Min-Naseerin (Idgham + Ghunnah)', ruleTag: 'nasal' },
      { id: 'l14-5', arabic: 'مِنْ رَّبِّكَ', transliteration: 'Mir-Rabbika (Idgham without Ghunnah)', ruleTag: 'shaddah' },
      { id: 'l14-6', arabic: 'مِنْ لَّدُنْهُ', transliteration: 'Mil-Ladunhu (Idgham without Ghunnah)', ruleTag: 'shaddah' },
      { id: 'l14-7', arabic: 'مِنْ بَعْدِ', transliteration: 'Mim-ba\'di (Iqlaab)', ruleTag: 'nasal' },
      { id: 'l14-8', arabic: 'أَنْبِئْهُمْ', transliteration: 'Ambi\'hum (Iqlaab)', ruleTag: 'nasal' },
      { id: 'l14-9', arabic: 'خَبِيرًا بَصِيرًا', transliteration: 'Khabeeram-Baseera (Iqlaab)', ruleTag: 'nasal' },
      { id: 'l14-10', arabic: 'صُمٌّ بُكْمٌ', transliteration: 'Summum-Bukmun (Iqlaab)', ruleTag: 'nasal' },
    ],
  },
  {
    id: 15,
    slug: 'meem-saakin',
    titleArabic: 'أَحْكَامُ الْمِيمِ السَّاكِنَة',
    titleEnglish: 'Rules of Meem Saakinah',
    stage: 4,
    stageTitle: 'Stage 4 · Recitation Rules & Fluency',
    estimatedMinutes: 20,
    summary: 'The 3 cases of Meem Saakin: Idgham Shafawi (مْ + م), Ikhfa Shafawi (مْ + ب), and Izhar Shafawi (remaining 26 letters).',
    keyRules: [
      'Idgham Shafawi: Meem Saakin followed by Meem (مْ + مّ) $\to$ Merge with Ghunnah (e.g. كَمْ مِنْ).',
      'Ikhfa Shafawi: Meem Saakin followed by Baa (مْ + ب) $\to$ Conceal with Ghunnah (e.g. تَرْمِيهِمْ بِحِجَارَةٍ).',
      'Izhar Shafawi: Meem Saakin followed by any of the other 26 letters $\to$ Pronounce clearly without Ghunnah.',
    ],
    pedagogicalTips: [
      'Be especially careful not to nasalize Meem Saakin before Faa (ف) or Waw (و) (e.g. هُمْ فِيْهَا).',
    ],
    tiles: [
      { id: 'l15-1', arabic: 'أَنْتُمْ مُظْلِمُونَ', transliteration: 'Antum-Mudhlimoon (Idgham Shafawi)', ruleTag: 'nasal' },
      { id: 'l15-2', arabic: 'وَلَكُمْ مَّا كَسَبْتُمْ', transliteration: 'Wa lakum-ma kasabtum (Idgham Shafawi)', ruleTag: 'nasal' },
      { id: 'l15-3', arabic: 'كُنْتُمْ بِهِ', transliteration: 'Kuntum-bihi (Ikhfa Shafawi)', ruleTag: 'nasal' },
      { id: 'l15-4', arabic: 'تَرْمِيهِمْ بِحِجَارَةٍ', transliteration: 'Tarmeehim-bihijaarah (Ikhfa Shafawi)', ruleTag: 'nasal' },
      { id: 'l15-5', arabic: 'أَلَمْ تَرَ', transliteration: 'Alam tara (Izhar Shafawi)', ruleTag: 'normal' },
      { id: 'l15-6', arabic: 'هُمْ فِيهَا', transliteration: 'Hum feeha (Izhar Shafawi)', ruleTag: 'normal' },
      { id: 'l15-7', arabic: 'لَمْ يَلِدْ', transliteration: 'Lam yalid (Izhar Shafawi)', ruleTag: 'normal' },
      { id: 'l15-8', arabic: 'لَكُمْ دِينُكُمْ', transliteration: 'Lakum deenukum (Izhar Shafawi)', ruleTag: 'normal' },
    ],
  },
  {
    id: 16,
    slug: 'tafkheem-tarqeeq',
    titleArabic: 'التَّفْخِيم وَالتَّرْقِيق',
    titleEnglish: 'Tafkheem & Tarqeeq (Heavy vs Light)',
    stage: 4,
    stageTitle: 'Stage 4 · Recitation Rules & Fluency',
    estimatedMinutes: 25,
    summary: 'Heavy (Tafkheem) vs Light (Tarqeeq) rules for the Letter Raa (ر), the Name of Allah (اللّٰهُ), and Alif.',
    keyRules: [
      'Laam of Allah: Pronounce HEAVY if preceded by Fathah or Dammah (وَاللّٰهُ / قَالُوا اللّٰهُ); pronounce LIGHT if preceded by Kasrah (بِسْمِ اللّٰهِ / لِلّٰهِ).',
      'Raa is HEAVY with Fathah/Dammah, or when Saakin preceded by Fathah/Dammah.',
      'Raa is LIGHT with Kasrah, or when Saakin preceded by original Kasrah.',
    ],
    pedagogicalTips: [
      'Fill the mouth with sound for heavy Laam; keep mouth neutral for light Laam.',
    ],
    tiles: [
      { id: 'l16-1', arabic: 'اللّٰهُ', transliteration: 'Allahu (Heavy)', ruleTag: 'heavy' },
      { id: 'l16-2', arabic: 'وَاللّٰهُ', transliteration: 'Wallahu (Heavy)', ruleTag: 'heavy' },
      { id: 'l16-3', arabic: 'إِنَّ اللّٰهَ', transliteration: 'Innallaha (Heavy)', ruleTag: 'heavy' },
      { id: 'l16-4', arabic: 'بِسْمِ اللّٰهِ', transliteration: 'Bismillahi (Light)', ruleTag: 'normal' },
      { id: 'l16-5', arabic: 'لِلّٰهِ', transliteration: 'Lillahi (Light)', ruleTag: 'normal' },
      { id: 'l16-6', arabic: 'رَسُولُ اللّٰهِ', transliteration: 'Rasoolullahi (Heavy)', ruleTag: 'heavy' },
      { id: 'l16-7', arabic: 'رَجُلٌ', transliteration: 'Rajulun (Heavy Raa)', ruleTag: 'heavy' },
      { id: 'l16-8', arabic: 'رِجَالٌ', transliteration: 'Rijaalun (Light Raa)', ruleTag: 'normal' },
      { id: 'l16-9', arabic: 'مِرْصَادٌ', transliteration: 'Mirsaad (Heavy Raa before heavy letter)', ruleTag: 'heavy' },
      { id: 'l16-10', arabic: 'فِرْعَوْنَ', transliteration: 'Fir\'awn (Light Raa)', ruleTag: 'normal' },
    ],
  },
  {
    id: 17,
    slug: 'maddaat',
    titleArabic: 'أَحْكَامُ الْمُدُود',
    titleEnglish: 'The System of Madd (Elongations)',
    stage: 4,
    stageTitle: 'Stage 4 · Recitation Rules & Fluency',
    estimatedMinutes: 25,
    summary: 'Madd Muttasil (Connected, 4-5 counts), Madd Munfasil (Separated, 4-5 counts), Madd Lazim (Mandatory, 6 counts), and Madd Aaridh (Stopping, 2-6 counts).',
    keyRules: [
      'Madd Muttasil: Madd letter followed by Hamzah in the SAME word $\to$ 4–5 counts (جَاءَ).',
      'Madd Munfasil: Madd letter followed by Hamzah in the NEXT word $\to$ 4–5 counts (فِي أَنْفُسِكُمْ).',
      'Madd Lazim: Madd letter followed by permanent Sukoon/Shaddah $\to$ Full 6 counts (جَانَّ / وَلَا الضَّالِّينَ).',
      'Madd \'Aaridh: Temporary Sukoon due to stopping $\to$ 2, 4, or 6 counts (الْعَالَمِينَ).',
    ],
    pedagogicalTips: [
      'Count Harakaat evenly without excessive speed or sluggishness.',
    ],
    tiles: [
      { id: 'l17-1', arabic: 'جَاءَ', transliteration: 'Jaa\'a (Muttasil 4-5)', ruleTag: 'madd' },
      { id: 'l17-2', arabic: 'سُوءَ', transliteration: 'Soo\'a (Muttasil 4-5)', ruleTag: 'madd' },
      { id: 'l17-3', arabic: 'أُولٰئِكَ', transliteration: 'Ulaa\'ika (Muttasil 4-5)', ruleTag: 'madd' },
      { id: 'l17-4', arabic: 'بِمَا أُنْزِلَ', transliteration: 'Bimaa unzila (Munfasil 4-5)', ruleTag: 'madd' },
      { id: 'l17-5', arabic: 'قَالُوا آمَنَّا', transliteration: 'Qaaloo aamanna (Munfasil 4-5)', ruleTag: 'madd' },
      { id: 'l17-6', arabic: 'دَابَّةٍ', transliteration: 'Daabbah (Lazim 6 counts)', ruleTag: 'madd' },
      { id: 'l17-7', arabic: 'جَانَّ', transliteration: 'Jaann (Lazim 6 counts)', ruleTag: 'madd' },
      { id: 'l17-8', arabic: 'وَلَا الضَّالِّينَ', transliteration: 'Walad-daalleen (Lazim 6 counts)', ruleTag: 'madd' },
      { id: 'l17-9', arabic: 'الْعَالَمِينَ', transliteration: 'Al-\'Aalameen (\'Aaridh 2-6 on stop)', ruleTag: 'madd' },
      { id: 'l17-10', arabic: 'نَسْتَعِينُ', transliteration: 'Nasta\'een (\'Aaridh 2-6 on stop)', ruleTag: 'madd' },
    ],
  },
  {
    id: 18,
    slug: 'muqattaat',
    titleArabic: 'الْحُرُوفُ الْمُقَطَّعَات',
    titleEnglish: 'Huroof Muqatta\'at (Disjointed Letters)',
    stage: 4,
    stageTitle: 'Stage 4 · Recitation Rules & Fluency',
    estimatedMinutes: 20,
    summary: 'The disjointed opening letters of Quranic Surahs. Spell letter names fully while applying Madd Lazim (6 counts) and internal Ghunnah.',
    keyRules: [
      'Pronounce each letter by its full spelling name (e.g. الم $\to$ Alif Laam Meem).',
      'Stretch letters containing 3-letter names (Laam, Meem, Saad, Qaaf, Kaaf, Seen, Ayn, Noon) for full 6 counts.',
      'Stretch 2-letter names (Haa, Yaa, Taa, Haa, Raa - حَيٌّ طَهُرَ) for 2 counts.',
      'Apply Ghunnah on internal Idgham/Ikhfa (e.g. between Laam and Meem in الٓمٓ).',
    ],
    pedagogicalTips: [
      'Alif (أَلِف) has no elongation.',
    ],
    tiles: [
      { id: 'l18-1', arabic: 'الٓمٓ', transliteration: 'Alif Laaam Mmeeem', spelledArabic: 'أَلِف لَام مِيم' },
      { id: 'l18-2', arabic: 'الٓمٓصٓ', transliteration: 'Alif Laaam Mmeeem Saaad', spelledArabic: 'أَلِف لَام مِيم صَاد' },
      { id: 'l18-3', arabic: 'الٓر', transliteration: 'Alif Laaam Raa', spelledArabic: 'أَلِف لَام رَا' },
      { id: 'l18-4', arabic: 'طٰهٰ', transliteration: 'Taa Haa (2 counts each)', spelledArabic: 'طَا هَا' },
      { id: 'l18-5', arabic: 'طٰسٓمٓ', transliteration: 'Taa Saaam Mmeeem', spelledArabic: 'طَا سِين مِيم' },
      { id: 'l18-6', arabic: 'يٰسٓ', transliteration: 'Yaa Saaaeen', spelledArabic: 'يَا سِين' },
      { id: 'l18-7', arabic: 'صٓ', transliteration: 'Saaad (6 counts)', spelledArabic: 'صَاد' },
      { id: 'l18-8', arabic: 'حٰمٓ', transliteration: 'Haa Mmeeem', spelledArabic: 'حَا مِيم' },
      { id: 'l18-9', arabic: 'عٓسٓقٓ', transliteration: '\'Ayyyn Seeen Qaaaf', spelledArabic: 'عَيْن سِين قَاف' },
      { id: 'l18-10', arabic: 'كٓهٰيٰعٓصٓ', transliteration: 'Kaaaf Haa Yaa \'Ayyyn Saaad', spelledArabic: 'كَاف هَا يَا عَيْن صَاد' },
      { id: 'l18-11', arabic: 'قٓ', transliteration: 'Qaaaf (6 counts)', spelledArabic: 'قَاف' },
      { id: 'l18-12', arabic: 'نٓ', transliteration: 'Nooon (6 counts)', spelledArabic: 'نُون' },
    ],
  },
  {
    id: 19,
    slug: 'zaid-alif',
    titleArabic: 'الْأَلِفُ الزَّائِدَة',
    titleEnglish: 'Za\'id (Additional) Alif Rules',
    stage: 4,
    stageTitle: 'Stage 4 · Recitation Rules & Fluency',
    estimatedMinutes: 15,
    summary: 'The circular zero sign (ْ or ۬) on Alif in the Quran. Rules for pronouncing during Waqf (stop) vs dropping in Wasl (continuation).',
    keyRules: [
      'In 6 words (لٰكِنَّا ، الظُّنُونَا ، الرَّسُولَا ، السَّبِيلَا ، قَوَارِيرَا [1st] ، أَنَا): Drop the Alif when continuing (Wasl), but pronounce when stopping (Waqf).',
      'Other additional Alifs (e.g. أَفَإِنْ مَّاتَ ، مَلَإِيْهِ): Never pronounced in either Wasl or Waqf.',
    ],
    pedagogicalTips: [
      'Whenever reading أَنَا in recitation, always read as "Ana" (short vowel) unless stopping.',
    ],
    tiles: [
      { id: 'l19-1', arabic: 'أَنَا۠', transliteration: 'Ana (Short in Wasl)', ruleNote: 'Drop Alif when continuing' },
      { id: 'l19-2', arabic: 'لٰكِنَّا۠', transliteration: 'Laakinna (Al-Kahf: 38)', ruleNote: 'Pronounced on stop only' },
      { id: 'l19-3', arabic: 'الظُّنُونَا۠', transliteration: 'Adh-Dhunoona (Al-Ahzab: 10)' },
      { id: 'l19-4', arabic: 'الرَّسُولَا۠', transliteration: 'Ar-Rasoola (Al-Ahzab: 66)' },
      { id: 'l19-5', arabic: 'السَّبِيلَا۠', transliteration: 'As-Sabeela (Al-Ahzab: 67)' },
      { id: 'l19-6', arabic: 'قَوَارِيرَا۠', transliteration: 'Qawaareera (1st - Al-Insan: 15)' },
    ],
  },
  {
    id: 20,
    slug: 'misc-rules',
    titleArabic: 'قَوَاعِدُ مُتَفَرِّقَة',
    titleEnglish: 'Miscellaneous Tajweed Rules',
    stage: 4,
    stageTitle: 'Stage 4 · Recitation Rules & Fluency',
    estimatedMinutes: 20,
    summary: 'Izhar-e-Mutlaq (4 words: دُنْيَا ، بُنْيَان ، صِنْوَان ، قِنْوَان), Saktah (breath-held pause in 4 places), Tasheel, Imalah, and Noon Qutni.',
    keyRules: [
      'Izhar-e-Mutlaq: In 4 words (دُنْيَا ، بُنْيَانٌ ، صِنْوَانٌ ، قِنْوَانٌ), do NOT do Idgham; read clearly without Ghunnah.',
      'Saktah: Pause the voice for 1 second WITHOUT taking a breath (Wajib in 4 Quranic places: Kahf: 1, Yaseen: 52, Qiyamah: 27, Mutaffifeen: 14).',
      'Imalah: Incline Fathah towards Kasrah (Hood: 41 - مَجْر۪ىٰهَا pronounced Maj-ray-ha).',
      'Tasheel: Soften the 2nd Hamzah (Fussilat: 44 - ءَ۬اعْجَمِيٌّ).',
      'Noon Qutni: Small Noon Kasrah inserted when connecting Tanween to Hamzah Wasl (e.g. شَيْئًا ۨالسَّمَاءِ).',
    ],
    pedagogicalTips: [
      'Practice holding breath precisely during the Saktah pause.',
    ],
    tiles: [
      { id: 'l20-1', arabic: 'دُنْيَا', transliteration: 'Dunya (Izhar Mutlaq)', ruleTag: 'normal' },
      { id: 'l20-2', arabic: 'بُنْيَانٌ', transliteration: 'Bunyaan (Izhar Mutlaq)', ruleTag: 'normal' },
      { id: 'l20-3', arabic: 'صِنْوَانٌ', transliteration: 'Sinwaan (Izhar Mutlaq)', ruleTag: 'normal' },
      { id: 'l20-4', arabic: 'قِنْوَانٌ', transliteration: 'Qinwaan (Izhar Mutlaq)', ruleTag: 'normal' },
      { id: 'l20-5', arabic: 'عِوَجًا ۜ قَيِّمًا', transliteration: '\'Iwajaa [Saktah] Qayyima', ruleNote: '1s pause without breath' },
      { id: 'l20-6', arabic: 'مِنْ مَّرْقَدِنَا ۜ هٰذَا', transliteration: 'Mim-marqadinaa [Saktah] Haadhaa', ruleNote: 'Surah Yaseen: 52' },
      { id: 'l20-7', arabic: 'كَلَّا بَلْ ۜ رَانَ', transliteration: 'Kalla bal [Saktah] Raana', ruleNote: 'Al-Mutaffifeen: 14' },
      { id: 'l20-8', arabic: 'وَقِيلَ مَنْ ۜ رَاقٍ', transliteration: 'Wa qeela man [Saktah] Raaq', ruleNote: 'Al-Qiyamah: 27' },
      { id: 'l20-9', arabic: 'مَجْر۪ىٰهَا', transliteration: 'Majrayhaa (Imalah)', ruleNote: 'Hood: 41' },
      { id: 'l20-10', arabic: 'ءَ۬اعْجَمِيٌّ', transliteration: 'Aa\'jamiyy (Tasheel)', ruleNote: 'Fussilat: 44' },
      { id: 'l20-11', arabic: 'بِئْسَ الِاسْمُ', transliteration: 'Bi\'sal-ismu', ruleNote: 'Al-Hujurat: 11' },
    ],
  },
  {
    id: 21,
    slug: 'waqf-rules',
    titleArabic: 'أَحْكَامُ الْوَقْف',
    titleEnglish: 'Rules of Waqf (Stopping)',
    stage: 4,
    stageTitle: 'Stage 4 · Recitation Rules & Fluency',
    estimatedMinutes: 20,
    summary: 'How to stop at the end of verses and words. Changing Harakaat to Sukoon, Tanween Fathah to Alif, Taa Marbutah (ة) to Haa (هـ), and Waqf symbols.',
    keyRules: [
      'Short vowels (َ ِ ُ) and double vowels (ٍ ٌ) become SAAKIN on stop.',
      'Double Fathah (ً) changes to a 2-count ALIF (e.g. عَلِيمًا $\to$ Aleemaa).',
      'Round Taa (ة / ـة) ALWAYS changes to a silent Haa (هـْ) on stop (e.g. جَارِيَةٌ $\to$ Jaariyah).',
      'Pause symbols: ۝ (Ayah stop), م (Wajib stop), ط (Better to stop), ج (Permissible stop), لا (Do not stop).',
    ],
    pedagogicalTips: [
      'Stop both the sound and the breath at the pause.',
    ],
    tiles: [
      { id: 'l21-1', arabic: 'نَسْتَعِينُ ۝', transliteration: 'Nasta\'een (Becomes Saakin)', ruleNote: 'Dammah $\to$ Sukoon' },
      { id: 'l21-2', arabic: 'عَلِيمًا ۝', transliteration: '\'Aleemaa (Becomes Alif)', ruleNote: 'Fathatayn $\to$ Alif' },
      { id: 'l21-3', arabic: 'جَارِيَةٌ ۝', transliteration: 'Jaariyah (Becomes Haa)', ruleNote: 'Taa Marbutah $\to$ Haa' },
      { id: 'l21-4', arabic: 'أَلْفَافًا ۝', transliteration: 'Alfaafaa', ruleNote: 'Double Fathah $\to$ Alif' },
      { id: 'l21-5', arabic: 'قَدِيرٌ ۝', transliteration: 'Qadeer', ruleNote: 'Double Dammah $\to$ Sukoon' },
      { id: 'l21-6', arabic: 'بِأَمْرِهِ ۝', transliteration: 'Bi\'amrih', ruleNote: 'Kasrah $\to$ Sukoon' },
      { id: 'l21-7', arabic: 'رَقَبَةٍ ۝', transliteration: 'Raqabah', ruleNote: 'Taa Marbutah $\to$ Haa' },
      { id: 'l21-8', arabic: 'فَتَرْضَىٰ ۝', transliteration: 'Fatardaa', ruleNote: 'Madd remains unchanged' },
    ],
  },
  {
    id: 22,
    slug: 'salah-application',
    titleArabic: 'تَطْبِيقُ الصَّلَاة',
    titleEnglish: 'Complete Recitation in Daily Salah',
    stage: 4,
    stageTitle: 'Stage 4 · Recitation Rules & Fluency',
    estimatedMinutes: 30,
    summary: 'The ultimate culmination of the Qa\'idah. Apply every Tajweed & phonetic rule to the complete prayers of Salah.',
    keyRules: [
      'Apply every single learned rule: Makharij, Harakaat, Madd, Qalqala, Ghunnah, and Waqf.',
      'Correct differentiation is mandatory for the validity of Salah.',
    ],
    pedagogicalTips: [
      'Read slowly with reflection and pristine phonetic precision.',
    ],
    tiles: [
      { id: 'l22-1', arabic: 'اللّٰهُ أَكْبَرُ', transliteration: 'Allahu Akbar (Takbeer)', englishMeaning: 'Allah is the Greatest' },
      { id: 'l22-2', arabic: 'سُبْحَانَكَ اللّهُمَّ وَبِحَمْدِكَ وَتَبَارَكَ اسْمُكَ وَتَعَالَىٰ جَدُّكَ وَلَا إِلٰهَ غَيْرُكَ', transliteration: 'Subhaanakallahumma wa bihamdika...', englishMeaning: 'The Opening Sana' },
      { id: 'l22-3', arabic: 'أَعُوذُ بِاللّٰهِ مِنَ الشَّيْطَانِ الرَّجِيمِ', transliteration: 'A\'oodhu billahi minash-shaytaanir-rajeem', englishMeaning: 'Seeking Refuge' },
      { id: 'l22-4', arabic: 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيمِ', transliteration: 'Bismillahir-Rahmaanir-Raheem', englishMeaning: 'In the Name of Allah' },
      { id: 'l22-5', arabic: 'الْحَمْدُ لِلّٰهِ رَبِّ الْعَالَمِينَ ۝', transliteration: 'Alhamdu lillahi Rabbil-\'Aalameen', englishMeaning: 'Surah Al-Fatihah' },
      { id: 'l22-6', arabic: 'الرَّحْمٰنِ الرَّحِيمِ ۝', transliteration: 'Ar-Rahmaanir-Raheem', englishMeaning: 'The Entirely Merciful' },
      { id: 'l22-7', arabic: 'مَالِكِ يَوْمِ الدِّينِ ۝', transliteration: 'Maaliki Yawmid-Deen', englishMeaning: 'Sovereign of Day of Recompense' },
      { id: 'l22-8', arabic: 'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ۝', transliteration: 'Iyyaaka na\'budu wa iyyaaka nasta\'een', englishMeaning: 'You alone we worship' },
      { id: 'l22-9', arabic: 'اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ ۝', transliteration: 'Ihdinas-Siraatal-Mustaqeem', englishMeaning: 'Guide us to the straight path' },
      { id: 'l22-10', arabic: 'صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ ۝ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ ۝', transliteration: 'Siraatal-ladheena an\'amta \'alayhim...', englishMeaning: 'The path of those You blessed' },
      { id: 'l22-11', arabic: 'قُلْ هُوَ اللّٰهُ أَحَدٌ ۝ اللّٰهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ ۝', transliteration: 'Surah Al-Ikhlas', englishMeaning: 'The Sincerity' },
      { id: 'l22-12', arabic: 'التَّحِيَّاتُ لِلّٰهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللّٰهِ وَبَرَكَاتُهُ', transliteration: 'Attahiyyaatu lillahi...', englishMeaning: 'Tashahhud (Part 1)' },
      { id: 'l22-13', arabic: 'اللّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ', transliteration: 'Durood Ibraheem', englishMeaning: 'Salutations upon the Prophet' },
    ],
  },
];
